version: 2
updates:

  - package-ecosystem: "nuget" 
    directory: "/01-Starter-Seed" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "nuget" 
    directory: "/02-Authorization" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
